# yaml-language-server: $schema=https://schemas.trainquery.com/v2/config.schema.json

shared:
  stops: ./stops.yml
  lines: ./lines.yml
  urlNames: ./url-names.yml
  continuation: ./continuation.yml
  locations: ./locations.yml

  usePlatforms: true

  timezone:
    id: Australia/Melbourne
    offsetCheckHour: 12

  serviceTypes:
    - id: suburban
      mode: suburban-train
    - id: regional
      mode: regional-train

server:
  timetables: ./timetables/*.ttbl
  platformRules: ./platform-rules.yml
  gtfs: ./gtfs.yml
  ptv: ./ptv.yml
  banners: ./banners.yml
  linter: ./linter.yml

  # Don't send the about page markup to the client until they request it.
  about: ./about.md
  legal: ./legal.yml

  # disruptionSources:
  #   ptvApi:
  #     fetchFrequencyMins: 10
  #     fetchInProdOnly: true
  #
  # ...

frontend:
  appName: TrainQuery
  beta: true
  tagline: Navigate Melbourne's train network
  welcomeMarkdown: "TrainQuery is an unofficial guide to help you navigate Melbourne's train network. You can search for any suburban or regional train station to view upcoming departures, and adjust the departure time or filter to further refine the results.\n\nGet started using the search bar above."
  footerMarkdown: "© 2023-present Dan Schellekens — Not affiliated with PTV, Metro, V/Line, Transport Victoria, etc. For official timetables visit [transport.vic.gov.au](https://transport.vic.gov.au/)."
  metaDescription: Navigate Melbourne's train network with TrainQuery.
  departureFeeds: ./departure-feeds.yml

  via:
    - text: via Flinders Street
      # Prevent Gippsland line services needlessly being shown as "via Flinders Street".
      # 104 = Flinders Street
      rules: will-stop-at-104 continues

    - text: via City Loop
      # Must stop at all three (otherwise use commas).
      # 101 = Flagstaff
      # 171 = Melbourne Central
      # 216 = Parliament
      rules: will-stop-at-101 will-stop-at-171 will-stop-at-216

    - text: via Traralgon
      # 278 = Traralgon
      rules: direction-down will-stop-at-278

    - text: via Seymour
      # 244 = Seymour
      rules: direction-down will-stop-at-244

    - text: via Bendigo
      # 29 = Bendigo
      rules: direction-down will-stop-at-29

    - text: via Ballarat
      # 20 = Ballarat
      rules: direction-down will-stop-at-20

    - text: via Geelong
      # 110 = Geelong
      rules: direction-down will-stop-at-110

  directionNames:
    up:
      regular: citybound
      capital: Citybound

    down:
      regular: outbound
      capital: Outbound

    clockwise:
      regular: clockwise
      capital: Clockwise

    anticlockwise:
      regular: anti-clockwise
      capital: Anti-clockwise
