# yaml-language-server: $schema=../schemas/config-v1.schema.json

shared:
  stops: ./stops.yml
  lines: ./lines.yml
  urlNames: ./url-names.yml

  usePlatforms: true

  timezone:
    id: Australia/Melbourne
    offsetCheckHour: 12

  serviceTypes:
    - id: suburban
      mode: suburban-train
    - id: regional
      mode: regional-train

server:
  timetables: ./timetables/*.ttbl
  continuation: ./continuation.yml
  platformRules: ./platform-rules.yml
  linter: ./linter.yml

  # Don't send the about page markup to the client until they request it.
  about: ./about.md

  # disruptionSources:
  #   ptvApi:
  #     fetchFrequencyMins: 10
  #     fetchInProdOnly: true
  #
  # ...

frontend:
  appName: TrainQuery
  beta: true
  tagline: Navigate Melbourne's train network
  footer: '© Dan Schellekens 2023 &mdash; Not affiliated with PTV, Metro Trains Melbourne, or V/Line. Data accuracy cannot be guaranteed. For official timetables visit <a href="https://www.ptv.vic.gov.au" class="link">ptv.vic.gov.au</a>.'
  metaDescription: Navigate Melbourne's train network with TrainQuery.
  departureFeeds: ./departure-feeds.yml

  via:
    - text: via Flinders Street
      stops:
        - 104 # Flinders Street

      # Prevent citybound Gippsland line services needlessly being shown as "via Flinders Street".
      onlyIfContinuing: true

    - text: via City Loop
      stops:
        - 101 # Flagstaff
        - 171 # Melbourne Central
        - 216 # Parliament
  directionNames:
    up:
      regular: citybound
      capital: Citybound
    down:
      regular: outbound
      capital: Outbound
